name: flutter_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  dio: 4.0.4
  pull_to_refresh: 2.0.0
  shared_preferences: 2.0.12
  flutter_slidable: 1.2.0
  flutter_easyloading: ^3.0.3
  badges: ^2.0.2
  city_pickers: 1.0.1
  intl: ^0.17.0
  flutter_swiper_null_safety: ^1.0.2

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/images/icon/
    - assets/images/tabs/
    - assets/images/tabs/profile/
    - assets/images/tabs/cart/

  uses-material-design: true

